### ISSUE TITLE
Add github actions for CI

### ISSUE THREAD

**Issue by bluss** [bluss/scopeguard#27]
We need github actions so that we can check PRs and also consciously track the MSRV. Stretch goal is to test no-std support, too.

**Comment by bluss** [comment]
Thanks. To be precise, the stretch goal is still open since we don't yet check conclusively that it builds successfully on a non-std platform (std could be used unintentionally and it would not be detected).

**Comment by konsumlamm** [comment]
Ah, I see. This shouldn't be a problem since we have no dependencies that could use `std` and to accidentally use it, someone would have to do `extern crate std` (which seems unlikely to me). Unfortunately, I don't think GitHub actions support no_std platforms. 

Feel free to reopen this issue for the stretch goal.

**Comment by Amanieu** [comment]
The easiest way to test no_std is to install the `thumbv6m-none-eabi` target with rustup and then try to cross-compile to that.
